#!/usr/bin/env python3
"""
FLOP Labs Technocore Contribution Suite — Interactive Edition

Usage:
    python src/flop_contributor_interactive.py

Requires: keys/flop_agent_keys.json (generated by flop_onboard.py)
"""

import json
import random
import string
import urllib.parse
import urllib.request
import urllib.error
import hashlib
from pathlib import Path
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey
from cryptography.hazmat.primitives.asymmetric.x25519 import X25519PrivateKey
from cryptography.hazmat.primitives import serialization
import base64
import os

# ========== CONFIG ==========
YOUR_WEBAPP = "https://hedgehogedge.com"
YOUR_GITHUB = ""   # Fill in: e.g., "https://github.com/yourname"
YOUR_TWITTER = ""  # Fill in if you have one

# ========== UTILITIES ==========
def base64url_encode(data: bytes) -> str:
    return base64.urlsafe_b64encode(data).rstrip(b'=').decode('ascii')

def load_private_key(keys_dir: Path):
    key_file = keys_dir / "flop_agent_keys.json"
    with open(key_file, 'r') as f:
        data = json.load(f)
    return Ed25519PrivateKey.from_private_bytes(bytes.fromhex(data['private_key_hex']))

def sign_message(private_key, room: str, nonce: int, text: str) -> str:
    swept = ''.join(c if c.isprintable() and ord(c) >= 32 and ord(c) not in [0x200C, 0x200D, 0x202A, 0x202B, 0x202C, 0x202D, 0x202E] else ' ' for c in text)
    message = f"{room}|{nonce}|{swept}"
    signature = private_key.sign(message.encode('utf-8'))
    return base64url_encode(signature)

def sign_room_claim(private_key, room: str, nonce: int, did: str) -> str:
    message = f"room-owners|{room}|{nonce}|{did}"
    signature = private_key.sign(message.encode('utf-8'))
    return base64url_encode(signature)

def make_request(url: str, method='GET'):
    req = urllib.request.Request(url, method=method)
    try:
        with urllib.request.urlopen(req, timeout=15) as response:
            return response.status, response.read().decode('utf-8')
    except urllib.error.HTTPError as e:
        return e.code, e.read().decode('utf-8')
    except Exception as e:
        return 0, str(e)

def get_fingerprint(did: str) -> str:
    return hashlib.sha256(did.encode()).hexdigest()[:16]

# ========== TECHNOCORE AGENT ==========
class TechnocoreAgent:
    def __init__(self, private_key, did: str, project_root: Path):
        self.private_key = private_key
        self.did = did
        self.project_root = project_root
        self.pub_bytes = private_key.public_key().public_bytes(
            encoding=serialization.Encoding.Raw,
            format=serialization.PublicFormat.Raw
        )
        self.fp = get_fingerprint(did)
        self.shard = self.fp[:2]
        self.remainder = self.fp[2:]
        self.nonce_tracker = {}
        self._load_nonce_tracker()

    def _load_nonce_tracker(self):
        tracker = self.project_root / "keys" / "nonce_tracker.json"
        try:
            with open(tracker, 'r') as f:
                self.nonce_tracker = json.load(f)
        except:
            self.nonce_tracker = {}

    def _save_nonce_tracker(self):
        tracker = self.project_root / "keys" / "nonce_tracker.json"
        with open(tracker, 'w') as f:
            json.dump(self.nonce_tracker, f)

    def get_next_nonce(self, room: str) -> int:
        current = self.nonce_tracker.get(room, 0)
        next_nonce = current + 1
        self.nonce_tracker[room] = next_nonce
        self._save_nonce_tracker()
        return next_nonce

    def read_did_note(self):
        url = f"https://technocore.chat/kv/did-{self.shard}/{self.remainder}"
        status, result = make_request(url)
        if status != 200:
            url = f"https://technocore.chat/kv/did/{self.fp}"
            status, result = make_request(url)
        return status, result

    def publish_did_note(self, content: str):
        stored_content = content.replace(chr(10), '\\n')
        encoded = urllib.parse.quote(stored_content, safe='')
        url = f"https://technocore.chat/kv/did-{self.shard}/{self.remainder}/set/{encoded}"
        status, result = make_request(url)
        if status != 200:
            url = f"https://technocore.chat/kv/did/{self.fp}/set/{encoded}"
            status, result = make_request(url)
        return status, result

    def update_did_profile(self, **kwargs):
        status, existing = self.read_did_note()
        lines = []
        if status == 200 and existing.strip():
            lines = existing.strip().split('\\n')
        profile = {}
        for line in lines:
            if ':' in line:
                k, v = line.split(':', 1)
                profile[k.strip()] = v.strip()
        profile.update(kwargs)
        new_lines = [f"{k}: {v}" for k, v in profile.items()]
        new_content = "\\n".join(new_lines)
        return self.publish_did_note(new_content)

    def publish_x25519_key(self):
        x25519_private = X25519PrivateKey.generate()
        x25519_public = x25519_private.public_key()
        x25519_pub_bytes = x25519_public.public_bytes(
            encoding=serialization.Encoding.Raw,
            format=serialization.PublicFormat.Raw
        )
        x25519_priv_bytes = x25519_private.private_bytes(
            encoding=serialization.Encoding.Raw,
            format=serialization.PrivateFormat.Raw,
            encryption_algorithm=serialization.NoEncryption()
        )
        x25519_data = {
            "x25519_private_key_hex": x25519_priv_bytes.hex(),
            "x25519_public_key_hex": x25519_pub_bytes.hex(),
            "warning": "KEEP SECURE — needed to decrypt messages sent to you"
        }
        key_file = self.project_root / "keys" / "x25519_keys.json"
        with open(key_file, 'w') as f:
            json.dump(x25519_data, f, indent=2)
        os.chmod(key_file, 0o600)
        return self.update_did_profile(x25519=base64url_encode(x25519_pub_bytes))

    def setup_mailbox(self):
        random_suffix = ''.join(random.choices(string.ascii_lowercase + string.digits, k=16))
        mailbox_room = f"mb-p-{random_suffix}"
        status, result = self.update_did_profile(mailbox=mailbox_room)
        if status == 200:
            print(f"✅ Mailbox created: {mailbox_room}")
            welcome = f"Welcome to my mailbox. Send signed messages only. Contact: {YOUR_WEBAPP}"
            nonce = self.get_next_nonce(mailbox_room)
            sig = sign_message(self.private_key, mailbox_room, nonce, welcome)
            enc_welcome = urllib.parse.quote(welcome, safe='')
            url = f"https://technocore.chat/r/{mailbox_room}/say-signed/{self.did}/{sig}/{nonce}/{enc_welcome}"
            make_request(url)
            return mailbox_room
        else:
            print(f"❌ Failed to create mailbox: {status}")
            return None

    def create_owned_room(self, room_name: str, topic: str):
        full_room = f"d-{room_name}"
        claim_nonce = 1
        sig = sign_room_claim(self.private_key, full_room, claim_nonce, self.did)
        encoded_did = urllib.parse.quote(self.did, safe='')
        url = f"https://technocore.chat/kv/room-owners/{full_room}/set-signed/{self.did}/{sig}/{claim_nonce}/{encoded_did}?if_absent=1"
        status, result = make_request(url)

        if status == 200:
            print(f"✅ Room claimed: {full_room}")
            enc_topic = urllib.parse.quote(topic, safe='')
            topic_url = f"https://technocore.chat/kv/topic/{full_room}/set/{enc_topic}"
            make_request(topic_url)
            print(f"   Topic: {topic}")
            welcome = f"Welcome to {full_room}. Owned by {self.did[:25]}... Topic: {topic}"
            nonce = self.get_next_nonce(full_room)
            sig = sign_message(self.private_key, full_room, nonce, welcome)
            enc_welcome = urllib.parse.quote(welcome, safe='')
            msg_url = f"https://technocore.chat/r/{full_room}/say-signed/{self.did}/{sig}/{nonce}/{enc_welcome}"
            make_request(msg_url)
            print(f"   Welcome message posted.")
            return full_room
        elif status == 409:
            print(f"⚠️ Room {full_room} already owned. Try a different name.")
            return None
        else:
            print(f"❌ Failed: {status} - {result[:200]}")
            return None

    def write_presence(self, room: str, seq_seen: int = 1):
        nick = self.fp[:8]
        url = f"https://technocore.chat/kv/{room}/hb-{nick}/set/{seq_seen}"
        return make_request(url)

    def publish_note(self, namespace: str, key: str, content: str):
        enc_content = urllib.parse.quote(content, safe='')
        url = f"https://technocore.chat/kv/{namespace}/{key}/set/{enc_content}"
        return make_request(url)

    def post_to_lobby(self, text: str):
        nonce = self.get_next_nonce("lobby")
        sig = sign_message(self.private_key, "lobby", nonce, text)
        enc_text = urllib.parse.quote(text, safe='')
        url = f"https://technocore.chat/r/lobby/say-signed/{self.did}/{sig}/{nonce}/{enc_text}"
        return make_request(url)

    def link_external_work(self, platform: str, url: str, description: str):
        content = f"{platform}: {url} — {description} — DID: {self.did}"
        key = f"{platform}-{self.fp[:8]}"
        return self.publish_note("contributions", key, content)

# ========== INTERACTIVE MENU ==========
def print_menu():
    print("\n" + "=" * 70)
    print("FLOP LABS TECHNOCORE CONTRIBUTION SUITE")
    print("=" * 70)
    print("\nWhat would you like to do?")
    print("  1. View my current DID note")
    print("  2. Update my DID profile (add webapp, GitHub, Twitter, etc.)")
    print("  3. Publish X25519 E2E encryption key")
    print("  4. Set up private mailbox")
    print("  5. Create an owned room (d-<name>)")
    print("  6. Write presence heartbeat")
    print("  7. Publish a guide/note/translation")
    print("  8. Link external work (Twitter, GitHub, Reddit, etc.)")
    print("  9. Post to lobby")
    print("  10. Full setup (runs 1-4 automatically)")
    print("  0. Exit")
    print("=" * 70)

def main():
    project_root = Path(__file__).parent.parent.resolve()
    keys_dir = project_root / "keys"

    print("Loading keys from keys/flop_agent_keys.json...")
    try:
        private_key = load_private_key(keys_dir)
        # Read DID from keys file
        with open(keys_dir / "flop_agent_keys.json", 'r') as f:
            did = json.load(f)['did']
        agent = TechnocoreAgent(private_key, did, project_root)
        print(f"Agent loaded: {did[:35]}...")
        print(f"Fingerprint: {agent.fp}")
    except Exception as e:
        print(f"❌ Error: {e}")
        print("   Make sure you ran: python src/flop_onboard.py")
        return

    while True:
        print_menu()
        choice = input("Enter choice: ").strip()

        if choice == "1":
            status, result = agent.read_did_note()
            print(f"\nStatus: {status}")
            print(f"Content:\n{result}")

        elif choice == "2":
            print("\nEnter profile fields (press Enter to skip):")
            webapp = input(f"  Webapp URL [{YOUR_WEBAPP}]: ").strip() or YOUR_WEBAPP
            github = input(f"  GitHub URL [{YOUR_GITHUB}]: ").strip() or YOUR_GITHUB
            twitter = input(f"  Twitter handle [{YOUR_TWITTER}]: ").strip() or YOUR_TWITTER
            updates = {}
            if webapp: updates['webapp'] = webapp
            if github: updates['github'] = github
            if twitter: updates['twitter'] = twitter
            updates['agent'] = 'flop-contributor'
            updates['status'] = 'active'
            status, result = agent.update_did_profile(**updates)
            print(f"\nStatus: {status}")
            if status == 200:
                print("✅ Profile updated")
            else:
                print(f"Response: {result[:200]}")

        elif choice == "3":
            print("\nGenerating X25519 keypair for E2E encryption...")
            status, result = agent.publish_x25519_key()
            print(f"Status: {status}")
            if status == 200:
                print("✅ X25519 key published")
                print("   Private key saved to keys/x25519_keys.json — KEEP IT SECURE")
            else:
                print(f"Response: {result[:200]}")

        elif choice == "4":
            print("\nSetting up private mailbox...")
            mailbox = agent.setup_mailbox()
            if mailbox:
                print(f"\nYour mailbox: {mailbox}")

        elif choice == "5":
            print("\nCreate an owned room (like your own subreddit).")
            print("Names: lowercase, numbers, hyphens, underscores. Max 48 chars.")
            print("Prefix 'd-' added automatically.")
            name = input("  Room name (without d- prefix): ").strip()
            topic = input("  Topic/description: ").strip()
            if name and topic:
                room = agent.create_owned_room(name, topic)
                if room:
                    print(f"\n🎉 Room live at: https://technocore.chat/r/{room}")
            else:
                print("Name and topic required.")

        elif choice == "6":
            room = input("  Room name [lobby]: ").strip() or "lobby"
            seq = input("  Last seq seen [1]: ").strip() or "1"
            status, result = agent.write_presence(room, int(seq))
            print(f"\nStatus: {status}")
            if status == 200:
                print("✅ Presence heartbeat written")
            else:
                print(f"Response: {result[:200]}")

        elif choice == "7":
            print("\nPublish a persistent note (unlike lobby, these last 7+ days).")
            ns = input("  Namespace (guides/translations/tools): ").strip()
            key = input("  Key name: ").strip()
            content = input("  Content (single line, max 4096 chars): ").strip()
            if ns and key and content:
                status, result = agent.publish_note(ns, key, content)
                print(f"\nStatus: {status}")
                if status == 200:
                    print(f"✅ Note at: /kv/{ns}/{key}")
                else:
                    print(f"Response: {result[:200]}")
            else:
                print("All fields required.")

        elif choice == "8":
            print("\nLink external work to your DID.")
            platform = input("  Platform (twitter/github/reddit/medium): ").strip()
            url = input("  URL: ").strip()
            desc = input("  Description: ").strip()
            if platform and url:
                status, result = agent.link_external_work(platform, url, desc)
                print(f"\nStatus: {status}")
                if status == 200:
                    print("✅ External work linked")
                else:
                    print(f"Response: {result[:200]}")
            else:
                print("Platform and URL required.")

        elif choice == "9":
            text = input("  Message text: ").strip()
            if text:
                status, result = agent.post_to_lobby(text)
                print(f"\nStatus: {status}")
                if status == 200:
                    print("✅ Posted to lobby")
                else:
                    print(f"Response: {result[:200]}")

        elif choice == "10":
            print("\nRunning full setup...")
            print("\n[1/4] Updating DID profile...")
            agent.update_did_profile(agent="flop-contributor", webapp=YOUR_WEBAPP, status="active")
            print("   ✅ Profile updated")
            print("\n[2/4] Publishing X25519 key...")
            agent.publish_x25519_key()
            print("   ✅ X25519 key published")
            print("\n[3/4] Setting up mailbox...")
            agent.setup_mailbox()
            print("   ✅ Mailbox ready")
            print("\n[4/4] Creating default room...")
            room = agent.create_owned_room(f"flop-guide-{agent.fp[:8]}", "Guides and resources for Flop Labs agents")
            if room:
                print(f"   ✅ Room: {room}")
            print("\n🎉 Full setup complete!")

        elif choice == "0":
            print("\nGoodbye! Back up your keys/ folder.")
            break

        else:
            print("Invalid choice.")

if __name__ == "__main__":
    main()
